### ISSUE TITLE
transformations library and baxter end effector pose

### ISSUE THREAD

**Issue by ghanimmukhtar** [baxter-flowers/optitrack_publisher#1]
Hi There,

I am trying to do the calibration between the baxter robot and optitrack system using the ipython notebook, and I have couple of questions: 

1. How does the node ```optitrack_calibration.ipynb``` get the end effector position? How does it differentiate between the two end effectors? I am attaching the calibrator to the left end effector.

2. Which transformations library is used here? I have installed the one from [here](http://www.lfd.uci.edu/%7Egohlke/code/transformations.py.html) but it doesn't include the method ```distance``` which causes the node to fail at the line: 
```
if last_point is None or transformations.distance(pose_rg_robot, last_point)>min_dist
```
In the method ```record_calibration_points(continuous = True, duration=60, min_dist=0.01, max_dur=0.05)```

Thanks for your feedback
Ghanim

**Comment by ymollard** [comment]
Hi,

1. It gets the pose of the effector via tf. To change the arm, just change cell 6:
```
calib_frame_robot = 'right_gripper' # The frame used for calibration in the robot's frame
```
2. This is [that library](https://github.com/baxter-flowers/baxter_commander), just run the setup.py and re-open the notebook. I guess we have to get this module out of there, several people opened issues about this already.

**Comment by ghanimmukhtar** [comment]
Thanks for the answer I will test asap and let you know. Meanwhile I have another question, I don't if I should open a new issue or not. Anyway it is about the possibility of getting the position of single markers, is this possible with this package? Given that, of course, I don't care about the orientation just the raw position of a single marker in the robot frame?

**Comment by ymollard** [comment]
Nope this package does not track individual markers. I would even say they are not returned by Motive's VRPN server and that you must use Natnet instead, but I might be wrong, and it also depends of Motive versions.

I used this lib in the past to get individual markers from Natnet https://github.com/benureau/natnet
You can use this to publish a TF transform for each marker, now you have calibrated optitrack with respect wrt the robot.

**Comment by ghanimmukhtar** [comment]
So the calibration works fine now, thanks for the guidance, and yes, I think you are right, I had to use Natnet to stream the other markers. Anyway everything seem to work fine now.
